/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_appsync_graphqlEndpoint": "https://z2yzidcf5jdoppjhzwup7nlxdq.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_cognito_identity_pool_id": "eu-north-1:0fa29493-e739-44ef-ab6c-244c4f6fb7a1",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_UCjPS70rI",
    "aws_user_pools_web_client_id": "4m25htmmovbhu6c4gau4qlv0ts",
    "aws_appsync_apiKey": "da2-7ymtwc54hbhqlm5jjgq6xwpata",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "blogbucket134140-staging",
    "aws_user_files_s3_bucket_region": "eu-north-1"
};


export default awsmobile;
